package com.zeeb.luna.ui.screens.search

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.History
import androidx.compose.material.icons.filled.Search
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import androidx.paging.compose.collectAsLazyPagingItems
import com.zeeb.luna.data.db.LunaDatabase
import com.zeeb.luna.data.repository.MediaRepository
import com.zeeb.luna.ui.components.MediaGridItem
import com.zeeb.luna.ui.navigation.Screen

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SearchScreen(navController: NavController) {
	    val context = LocalContext.current
	        val db = LunaDatabase.getDatabase(context)
	            val repository = remember { MediaRepository(context, db) }
	                val viewModel = remember { SearchViewModel(repository, db) }

	                    val searchQuery by viewModel.searchQuery.collectAsState()
	                        val activeFilter by viewModel.activeFilter.collectAsState()
	                            val recentSearches by viewModel.recentSearches.collectAsState()
	                                val searchResults = viewModel.searchResults.collectAsLazyPagingItems()

	                                    Column(modifier = Modifier.fillMaxSize()) {
	                                    	        SearchBar(
	                                    	        	            query = searchQuery,
	                                    	        	                        onQueryChange = { viewModel.onQueryChange(it) },
	                                    	        	                                    onSearch = { viewModel.saveSearch(it) },
	                                    	        	                                                active = false,
	                                    	        	                                                            onActiveChange = {},
	                                    	        	                                                                        placeholder = { Text("Search photos, videos, albums...") },
	                                    	        	                                                                                    leadingIcon = { Icon(Icons.Default.Search, contentDescription = null) },
	                                    	        	                                                                                                modifier = Modifier.fillMaxWidth().padding(16.dp)
	                                    	        	                                                                                                        ) {}

	                                    	        	                                                                                                                LazyRow(
	                                    	        	                                                                                                                	            contentPadding = PaddingValues(horizontal = 16.dp),
	                                    	        	                                                                                                                	                        horizontalArrangement = Arrangement.spacedBy(8.dp),
	                                    	        	                                                                                                                	                                    modifier = Modifier.padding(bottom = 8.dp)
	                                    	        	                                                                                                                	                                            ) {
	                                    	        	                                                                                                                	                                            	            items(SearchFilter.values()) { filter ->
	                                    	        	                                                                                                                	                                            	                            FilterChip(
	                                    	        	                                                                                                                	                                            	                            	                    selected = activeFilter == filter,
	                                    	        	                                                                                                                	                                            	                            	                                        onClick = { viewModel.onFilterChange(filter) },
	                                    	        	                                                                                                                	                                            	                            	                                                            label = { Text(filter.name.lowercase().capitalize()) }
	                                    	        	                                                                                                                	                                            	                            	                                                                            )
	                                    	        	                                                                                                                	                                            	                            	                                                                                        }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                }

	                                    	        	                                                                                                                	                                            	                            	                                                                                                        if (searchQuery.isEmpty()) {
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	            // Tampilkan Recent Search
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        Column(modifier = Modifier.padding(16.dp)) {
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                    Text("Recent Searches", style = MaterialTheme.typography.titleSmall)
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                        Text("Clear", color = MaterialTheme.colorScheme.primary, modifier = Modifier.clickable { viewModel.clearHistory() })
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                        }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                        recentSearches.forEach { history ->
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            Row(
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                        modifier = Modifier.fillMaxWidth().clickable { viewModel.onQueryChange(history.query) }.padding(vertical = 12.dp),
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                verticalAlignment = androidx.compose.ui.Alignment.CenterVertically
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    ) {
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                        Icon(Icons.Default.History, contentDescription = null, tint = MaterialTheme.colorScheme.secondary)
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                Spacer(modifier = Modifier.width(12.dp))
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                        Text(history.query)
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                            }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                            }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                        }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                } else {
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	            // Hasil Grid (Re-use shared transition jika perlu, di sini dibuat simpel)
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        LazyVerticalGrid(
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                columns = GridCells.Fixed(3),
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                modifier = Modifier.fillMaxSize(),
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                contentPadding = PaddingValues(1.dp)
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            ) {
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                items(searchResults.itemCount) { index ->
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                    val media = searchResults[index]
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        if (media != null) {
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                        // Implementasi item tanpa shared element untuk kecepatan search
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                // (Atau bungkus dengan SharedTransitionScope jika ingin animasi sama)
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        Box(modifier = Modifier.padding(1.dp).aspectRatio(1f).clickable {
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                            navController.navigate(Screen.Viewer.createRoute(media.id))
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    }) {
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                            // Gunakan AsyncImage sederhana
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        coil.compose.AsyncImage(
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                model = media.uri,
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                contentDescription = null,
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                modifier = Modifier.fillMaxSize(),
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                                                contentScale = androidx.compose.ui.layout.ContentScale.Crop
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                                                                            )
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                                                                                                    }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                                                                                                                        }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                                                                                                                                        }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                                                                                                                                                    }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                                                                                                                                                            }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                                                                                                                                                                }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        	                                                                                                                                                                                                                                                }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    	                                                        )
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        	                                                    }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        	                                                                        })
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            	                                                        }}
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        	                                                            }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                	                        )
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    	                                                                                                                                }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            	                                                                    }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                	                                                                                            )}
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        	                }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        	                        }
	                                    	        	                                                                                                                	                                            	                            	                                                                                                        }
	                                    	        	                                                                                                                	                                            	                            )}
	                                    	        	                                                                                                                	                                            }
	                                    	        	                                                                                                                )
	                                    	        )
	                                    }
}
