package com.zeeb.luna.util

import android.content.ContentUris
import android.content.Context
import android.net.Uri
import android.provider.MediaStore
import com.zeeb.luna.data.db.entity.MediaItemEntity

object MediaStoreUtil {
	    private val EXTERNAL_CONTENT_URI: Uri = MediaStore.Files.getContentUri("external")

	        private val PROJECTION = arrayOf(
	        	        MediaStore.Files.FileColumns._ID,
	        	                MediaStore.Files.FileColumns.DATA,
	        	                        MediaStore.Files.FileColumns.DISPLAY_NAME,
	        	                                MediaStore.Files.FileColumns.MIME_TYPE,
	        	                                        MediaStore.Files.FileColumns.SIZE,
	        	                                                MediaStore.Files.FileColumns.WIDTH,
	        	                                                        MediaStore.Files.FileColumns.HEIGHT,
	        	                                                                MediaStore.Files.FileColumns.DATE_ADDED,
	        	                                                                        MediaStore.Files.FileColumns.DATE_MODIFIED,
	        	                                                                                MediaStore.Files.FileColumns.BUCKET_ID,
	        	                                                                                        MediaStore.Files.FileColumns.BUCKET_DISPLAY_NAME,
	        	                                                                                                MediaStore.Files.FileColumns.DURATION,
	        	                                                                                                        MediaStore.Files.FileColumns.MEDIA_TYPE
	        	                                                                                                            )

	        	                                                                                                                fun scanDeviceMedia(context: Context): List<MediaItemEntity> {
	        	                                                                                                                	        val mediaList = mutableListOf<MediaItemEntity>()

	        	                                                                                                                	                        val selection = "${MediaStore.Files.FileColumns.MEDIA_TYPE} = ? OR ${MediaStore.Files.FileColumns.MEDIA_TYPE} = ?"
	        	                                                                                                                	                                val selectionArgs = arrayOf(
	        	                                                                                                                	                                	            MediaStore.Files.FileColumns.MEDIA_TYPE_IMAGE.toString(),
	        	                                                                                                                	                                	                        MediaStore.Files.FileColumns.MEDIA_TYPE_VIDEO.toString()
	        	                                                                                                                	                                	                                )
	        	                                                                                                                	                                	                                        val sortOrder = "${MediaStore.Files.FileColumns.DATE_MODIFIED} DESC"

	        	                                                                                                                	                                	                                                context.contentResolver.query(
	        	                                                                                                                	                                	                                                	            EXTERNAL_CONTENT_URI,
	        	                                                                                                                	                                	                                                	                        PROJECTION,
	        	                                                                                                                	                                	                                                	                                    selection,
	        	                                                                                                                	                                	                                                	                                                selectionArgs,
	        	                                                                                                                	                                	                                                	                                                            sortOrder
	        	                                                                                                                	                                	                                                	                                                                    )?.use { cursor ->
	        	                                                                                                                	                                	                                                	                                                                                val idColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns._ID)
	        	                                                                                                                	                                	                                                	                                                                                            val dataColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.DATA)
	        	                                                                                                                	                                	                                                	                                                                                                        val nameColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.DISPLAY_NAME)
	        	                                                                                                                	                                	                                                	                                                                                                                    val mimeColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.MIME_TYPE)
	        	                                                                                                                	                                	                                                	                                                                                                                                val sizeColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.SIZE)
	        	                                                                                                                	                                	                                                	                                                                                                                                            val widthColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.WIDTH)
	        	                                                                                                                	                                	                                                	                                                                                                                                                        val heightColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.HEIGHT)
	        	                                                                                                                	                                	                                                	                                                                                                                                                                    val dateAddedColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.DATE_ADDED)
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                val dateModifiedColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.DATE_MODIFIED)
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                            val bucketIdColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.BUCKET_ID)
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                        val bucketNameColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.BUCKET_DISPLAY_NAME)
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                    val durationColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.DURATION)
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                val typeColumn = cursor.getColumnIndexOrThrow(MediaStore.Files.FileColumns.MEDIA_TYPE)

	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            while (cursor.moveToNext()) {
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                val id = cursor.getLong(idColumn)
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                val type = cursor.getInt(typeColumn)
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                val contentUri = ContentUris.withAppendedId(
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                    if (type == MediaStore.Files.FileColumns.MEDIA_TYPE_VIDEO) 
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                            MediaStore.Video.Media.EXTERNAL_CONTENT_URI 
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                else MediaStore.Images.Media.EXTERNAL_CONTENT_URI,
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                    id
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                    )

	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    mediaList.add(
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    MediaItemEntity(
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                        id = id,
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                uri = contentUri.toString(),
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                        path = cursor.getString(dataColumn) ?: "",
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                name = cursor.getString(nameColumn) ?: "Unknown",
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                        mimeType = cursor.getString(mimeColumn) ?: "image/jpeg",
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                size = cursor.getLong(sizeColumn),
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                        width = cursor.getInt(widthColumn),
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                height = cursor.getInt(heightColumn),
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                        duration = cursor.getLong(durationColumn),
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                dateAdded = cursor.getLong(dateAddedColumn) * 1000,
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                        dateTaken = cursor.getLong(dateModifiedColumn) * 1000,
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                bucketId = cursor.getLong(bucketIdColumn),
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                                        bucketName = cursor.getString(bucketNameColumn) ?: "Internal",
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                                                                mediaType = type
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                                                                                    )
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                                                                                                    )
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                                                                                                                }
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                                                                                                                        }
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                                                                                                                                return mediaList
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                                                                                                                                    }
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    	                                                                                                                                                                                                                                                                                                                                                                                                                    }
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    	                    )
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                	                                                                                                                    )
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            	                                                )
	        	                                                                                                                	                                	                                                	                                                                                                                                                                                                                                            }}
	        	                                                                                                                	                                	                                                )
	        	                                                                                                                	                                )
	        	                                                                                                                }
	        )
}
