plugins {
	    alias(libs.plugins.android.application)
	        alias(libs.plugins.kotlin.android)
	            alias(libs.plugins.kotlin.compose)
	                alias(libs.plugins.ksp)
	                }

	                android {
	                	    namespace = "com.zeeb.luna"
	                	        compileSdk = 35 // Mengikuti standar SDK terbaru untuk targetSdk 36

	                	            defaultConfig {
	                	            	        applicationId = "com.zeeb.luna"
	                	            	                minSdk = 29
	                	            	                        targetSdk = 36
	                	            	                                versionCode = 1
	                	            	                                        versionName = "1.0"

	                	            	                                                testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
	                	            	                                                    }

	                	            	                                                        buildTypes {
	                	            	                                                        	        release {
	                	            	                                                        	        	            isMinifyEnabled = true
	                	            	                                                        	        	                        isShrinkResources = true
	                	            	                                                        	        	                                    proguardFiles(
	                	            	                                                        	        	                                    	                getDefaultProguardFile("proguard-android-optimize.txt"),
	                	            	                                                        	        	                                    	                                "proguard-rules.pro"
	                	            	                                                        	        	                                    	                                            )
	                	            	                                                        	        	                                    	                                                    }
	                	            	                                                        	        	                                    	                                                        }

	                	            	                                                        	        	                                    	                                                            compileOptions {
	                	            	                                                        	        	                                    	                                                            	        sourceCompatibility = JavaVersion.VERSION_17
	                	            	                                                        	        	                                    	                                                            	                targetCompatibility = JavaVersion.VERSION_17
	                	            	                                                        	        	                                    	                                                            	                    }

	                	            	                                                        	        	                                    	                                                            	                        kotlinOptions {
	                	            	                                                        	        	                                    	                                                            	                        	        jvmTarget = "17"
	                	            	                                                        	        	                                    	                                                            	                        	            }

	                	            	                                                        	        	                                    	                                                            	                        	                buildFeatures {
	                	            	                                                        	        	                                    	                                                            	                        	                	        compose = true
	                	            	                                                        	        	                                    	                                                            	                        	                	            }
	                	            	                                                        	        	                                    	                                                            	                        	                	            }

	                	            	                                                        	        	                                    	                                                            	                        	                	            dependencies {
	                	            	                                                        	        	                                    	                                                            	                        	                	            	    // Core & Compose
	                	            	                                                        	        	                                    	                                                            	                        	                	            	        implementation(libs.androidx-core-ktx)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	            implementation(libs.androidx-activity-compose)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                implementation(platform(libs.androidx-compose-bom))
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                    implementation(libs.androidx-compose-ui)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                        implementation(libs.androidx-compose-ui-graphics)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                            implementation(libs.androidx-compose-ui-tooling-preview)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                implementation(libs.androidx-compose-material3)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                    implementation(libs.androidx-compose-material-icons-extended)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                        implementation(libs.androidx-compose-animation)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                            implementation(libs.androidx-compose-foundation)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                // Lifecycle & ViewModel
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                    implementation(libs.androidx-lifecycle-runtime-compose)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                        implementation(libs.androidx-lifecycle-viewmodel-compose)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                            // Navigation
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                implementation(libs.androidx-navigation-compose)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                    // Room
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                        implementation(libs.androidx-room-runtime)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                            implementation(libs.androidx-room-ktx)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                implementation(libs.androidx-room-paging)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                    ksp(libs.androidx-room-compiler)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                        // Paging 3
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                            implementation(libs.androidx-paging-runtime)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                implementation(libs.androidx-paging-compose)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                    // Coil
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                        implementation(libs.coil-compose)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                            implementation(libs.coil-gif)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                implementation(libs.coil-svg)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                    implementation(libs.coil-video)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                        // Media3
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                            implementation(libs.media3-exoplayer)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                implementation(libs.media3-ui)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                    implementation(libs.media3-session)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                        // WorkManager
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                            implementation(libs.androidx-work-runtime-ktx)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                                // Coroutines
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                                    implementation(libs.kotlinx-coroutines-android)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                                        // Accompanist
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                                            implementation(libs.accompanist-permissions)

	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                                                // Debugging
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                                                    debugImplementation(libs.androidx-compose-ui-tooling-preview)
	                	            	                                                        	        	                                    	                                                            	                        	                	            	                                                                                                                                                                    }
	                	            	                                                        	        	                                    	                                                            	                        	                	            }
	                	            	                                                        	        	                                    	                                                            	                        	                }
	                	            	                                                        	        	                                    	                                                            	                        }
	                	            	                                                        	        	                                    	                                                            }
	                	            	                                                        	        	                                    )
	                	            	                                                        	        }
	                	            	                                                        }
	                	            }
	                }
}
