package com.zeeb.luna.ui.screens.albums

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.grid.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import coil.compose.AsyncImage
import com.zeeb.luna.data.db.LunaDatabase
import com.zeeb.luna.data.repository.MediaRepository
import com.zeeb.luna.domain.model.Album
import com.zeeb.luna.util.FormatUtil

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AlbumsScreen(navController: NavController) {
	    val context = LocalContext.current
	        val repository = remember { MediaRepository(context, LunaDatabase.getDatabase(context)) }
	            val viewModel = remember { AlbumsViewModel(repository) }
	                val uiState by viewModel.uiState.collectAsState()

	                    Scaffold(
	                    	        topBar = {
	                    	        	            LargeTopAppBar(
	                    	        	            	                title = { Text("Albums", fontWeight = FontWeight.Bold) },
	                    	        	            	                                colors = TopAppBarDefaults.largeTopAppBarColors(
	                    	        	            	                                	                    containerColor = MaterialTheme.colorScheme.background
	                    	        	            	                                	                                    )
	                    	        	            	                                	                                                )
	                    	        	            	                                	                                                        }
	                    	        	            	                                	                                                            ) { padding ->
	                    	        	            	                                	                                                                    LazyVerticalGrid(
	                    	        	            	                                	                                                                    	            columns = GridCells.Fixed(2),
	                    	        	            	                                	                                                                    	                        modifier = Modifier.padding(padding),
	                    	        	            	                                	                                                                    	                                    contentPadding = PaddingValues(16.dp),
	                    	        	            	                                	                                                                    	                                                horizontalArrangement = Arrangement.spacedBy(16.dp),
	                    	        	            	                                	                                                                    	                                                            verticalArrangement = Arrangement.spacedBy(24.dp)
	                    	        	            	                                	                                                                    	                                                                    ) {
	                    	        	            	                                	                                                                    	                                                                    	            // Section: My Albums
	                    	        	            	                                	                                                                    	                                                                    	                        item(span = { GridItemSpan(2) }) {
	                    	        	            	                                	                                                                    	                                                                    	                        	                Text("My Albums", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
	                    	        	            	                                	                                                                    	                                                                    	                        	                            }

	                    	        	            	                                	                                                                    	                                                                    	                        	                                                    items(uiState.userAlbums) { album ->
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    AlbumItem(album = album) {
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                    navController.navigate("album_detail/${album.id}/${album.name}")
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                    }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                }

	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                            // Section: Smart Albums
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        item(span = { GridItemSpan(2) }) {
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                Spacer(modifier = Modifier.height(16.dp))
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                Divider()
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                Spacer(modifier = Modifier.height(16.dp))
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                Text("Utilities", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                            }

	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                        items(uiState.smartAlbums) { album ->
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        AlbumItem(album = album) {
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                    // Logic navigasi khusus smart album
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                    }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                        }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            }

	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            @Composable
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            fun AlbumItem(album: Album, onClick: () -> Unit) {
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    Column(
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	        modifier = Modifier
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                    .fillMaxWidth()
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                .clickable { onClick() }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    ) {
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        AsyncImage(
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	            model = album.coverUri,
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                        contentDescription = album.name,
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                    modifier = Modifier
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                    .aspectRatio(1f)
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                    .clip(RoundedCornerShape(12.dp)),
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                contentScale = ContentScale.Crop
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                        )
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                Spacer(modifier = Modifier.height(8.dp))
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        Text(
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	            text = album.name,
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                        style = MaterialTheme.typography.bodyLarge,
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                    fontWeight = FontWeight.Medium,
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                maxLines = 1
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                        )
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                                Text(
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                                	            text = "${album.itemCount} item • ${FormatUtil.formatFileSize(album.totalSize)}",
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                                	                        style = MaterialTheme.typography.labelMedium,
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                                	                                    color = MaterialTheme.colorScheme.secondary
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                                	                                            )
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                                	                                                }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                                	                                                }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        	                                                                )
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        	                                                                                                        )
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    	        )
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    	                                    }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            	    )
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        	                                                            }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        	                                                                                                        }}
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    	                                                                        }
	                    	        	            	                                	                                                                    	                                                                    	                        	                                                                    }}
	                    	        	            	                                	                                                                    	                                                                    	                        }
	                    	        	            	                                	                                                                    	                                                                    }
	                    	        	            	                                	                                                                    )}
	                    	        	            	                                )
	                    	        	            )
	                    	        }
	                    )
}
