package com.zeeb.luna.ui.screens.settings

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SettingsScreen(navController: NavController) {
	    var gridColumns by remember { mutableStateOf(3f) }
	        var showVideoDuration by remember { mutableStateOf(true) }
	            var trashDays by remember { mutableStateOf(30) }

	                Scaffold(
	                	        topBar = {
	                	        	            TopAppBar(
	                	        	            	                title = { Text("Settings") },
	                	        	            	                                navigationIcon = {
	                	        	            	                                	                    IconButton(onClick = { navController.popBackStack() }) {
	                	        	            	                                	                    	                        Icon(Icons.Default.ArrowBack, contentDescription = null)
	                	        	            	                                	                    	                                            }
	                	        	            	                                	                    	                                                            }
	                	        	            	                                	                    	                                                                        )
	                	        	            	                                	                    	                                                                                }
	                	        	            	                                	                    	                                                                                    ) { padding ->
	                	        	            	                                	                    	                                                                                            LazyColumn(modifier = Modifier.padding(padding)) {
	                	        	            	                                	                    	                                                                                            	            item {
	                	        	            	                                	                    	                                                                                            	            	                SettingsHeader(title = "Appearance")
	                	        	            	                                	                    	                                                                                            	            	                                SettingsSliderItem(
	                	        	            	                                	                    	                                                                                            	            	                                	                    label = "Grid Columns",
	                	        	            	                                	                    	                                                                                            	            	                                	                                        value = gridColumns,
	                	        	            	                                	                    	                                                                                            	            	                                	                                                            onValueChange = { gridColumns = it },
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                valueRange = 2f..5f,
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                    steps = 2
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                    )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    SettingsToggleItem(
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                    label = "Show Video Duration",
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                        checked = showVideoDuration,
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                            onCheckedChange = { showVideoDuration = it }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                            )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                        }

	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    item {
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                SettingsHeader(title = "Trash")
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                SettingsSelectItem(
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                    label = "Auto-delete after",
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                        value = "$trashDays Days",
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                            onClick = { /* Show Dialog */ }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                            )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                        }

	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    item {
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                SettingsHeader(title = "About")
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                ListItem(
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                    headlineContent = { Text("Luna Gallery") },
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                        supportingContent = { Text("Version 1.0 (v29-API)") }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                        )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        ListItem(
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                    headlineContent = { Text("Package Name") },
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                        supportingContent = { Text("com.zeeb.luna") }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                        )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                    }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                            }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                }

	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                @Composable
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                fun SettingsHeader(title: String) {
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    Text(
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	        text = title.uppercase(),
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                style = MaterialTheme.typography.labelMedium,
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                        color = MaterialTheme.colorScheme.primary,
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                modifier = Modifier.padding(start = 16.dp, top = 24.dp, bottom = 8.dp)
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    }

	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    @Composable
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    fun SettingsSliderItem(label: String, value: Float, onValueChange: (Float) -> Unit, valueRange: ClosedFloatingPointRange<Float>, steps: Int) {
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    ListItem(
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	        headlineContent = { Text(label) },
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                trailingContent = { Text(value.toInt().toString()) },
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        supportingContent = {
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	            Slider(value = value, onValueChange = onValueChange, valueRange = valueRange, steps = steps)
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                    }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        }

	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        @Composable
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        fun SettingsToggleItem(label: String, checked: Boolean, onCheckedChange: (Boolean) -> Unit) {
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    ListItem(
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	        headlineContent = { Text(label) },
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                trailingContent = { Switch(checked = checked, onCheckedChange = onCheckedChange) }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    }

	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    @Composable
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    fun SettingsSelectItem(label: String, value: String, onClick: () -> Unit) {
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    	    ListItem(
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    	    	        modifier = androidx.compose.foundation.clickable { onClick() },
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    	    	                headlineContent = { Text(label) },
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    	    	                        trailingContent = { Text(value, color = MaterialTheme.colorScheme.secondary) }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    	    	                            )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    	    	                            }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    	    )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    	                    }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        	    )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        	                        }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    	                        }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    	    )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    	                                    }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                	    )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        	                                                                                }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                	                                                                        )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    	                                )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                	                                                                                                    }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    	                                )
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    	                                                                                                    }
	                	        	            	                                	                    	                                                                                            	            	                                	                                                                                                                                    )
	                	        	            	                                	                    	                                                                                            	            	                                )
	                	        	            	                                	                    	                                                                                            	            }
	                	        	            	                                	                    	                                                                                            }}
	                	        	            	                                	                    }
	                	        	            	                                }
	                	        	            )
	                	        }
	                )
}
